# Generated by Django 3.1.1 on 2020-09-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourtDecision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_processo', models.CharField(max_length=30)),
                ('ementa', models.CharField(max_length=5000)),
                ('favor_contribuinte', models.CharField(max_length=1)),
                ('id_cliente', models.IntegerField()),
            ],
        ),
    ]
